#!/bin/bash
rm -frv build
make clean && make mrproper
mkdir -pv build/out/modules/pronto build/out/dt_image
export ARCH=arm
export CROSS_COMPILE=/storage/toolchains/arm-eabi-4.8-linaro/bin/arm-eabi-
export STRIP=/storage/toolchains/arm-eabi-4.8-linaro/bin/arm-eabi-strip
make carmilla-lefanu-53X_defconfig
make menuconfig && wait
cp .config arch/arm/configs/carmilla-lefanu-a500fu_defconfig
rm -frv build
make clean && make mrproper
echo Done!